# Generated by Django 5.0 on 2023-12-16 23:41

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='data e hora de início')),
                ('data_hora_fim', models.DateTimeField(verbose_name='data e hora de fim')),
                ('limite_reservas', models.PositiveIntegerField(default=100, verbose_name='limite de reservas')),
                ('valor_por_adulto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_por_crianca_6_a_12', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_por_crianca_0_a_5', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('qtd_max_adultos', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('qtd_max_criancas', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='data_reserva',
            new_name='data_final',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='qtd_criancas',
            new_name='qtd_criancas_0_a_5',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='valor',
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reserva',
            name='qtd_criancas_6_a_12',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reserva',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='usuarios.evento'),
        ),
    ]
