# Generated by Django 5.0 on 2023-12-16 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_evento_rename_data_reserva_reserva_data_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nome',
        ),
    ]
