# Generated by Django 5.0 on 2023-12-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_reserva_valor_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='foto',
            field=models.ImageField(blank=True, default='/images/unknown.png', null=True, upload_to='images/'),
        ),
    ]
