# Generated by Django 5.0 on 2023-12-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_reserva_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='foto',
        ),
        migrations.AddField(
            model_name='evento',
            name='foto',
            field=models.ImageField(blank=True, default='/images/unknown.png', null=True, upload_to='images/'),
        ),
    ]
