# Generated by Django 5.0 on 2023-12-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_reserva_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='qtd_criancas_6_a_12',
            new_name='qtd_criancas_6_a_10',
        ),
    ]
