# Generated by Django 5.0 on 2023-12-17 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_rename_qtd_criancas_6_a_12_reserva_qtd_criancas_6_a_10'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='qtd_criancas_6_a_10',
            new_name='qtd_criancas_6_a_12',
        ),
    ]
