# Generated by Django 5.0 on 2023-12-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_rename_qtd_criancas_6_a_10_reserva_qtd_criancas_6_a_12'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='valor_por_crianca_6_a_12',
            new_name='valor_por_crianca_6_a_10',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='qtd_criancas_6_a_12',
            new_name='qtd_criancas_6_a_10',
        ),
    ]
