# Generated by Django 5.0 on 2023-12-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_cep_cidade_estado_alter_cliente_foto_bairro_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sobrenome',
        ),
    ]
