# Generated by Django 5.0 on 2023-12-31 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_remove_customuser_sobrenome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='CPF ou CNPJ'),
        ),
        migrations.CreateModel(
            name='DiaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data do evento')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='usuarios.evento')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='hora de início')),
                ('limite_reservas', models.PositiveIntegerField(verbose_name='limite de reservas')),
                ('dia_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='usuarios.diaevento')),
            ],
        ),
    ]
