# Generated by Django 5.0 on 2023-12-31 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_reserva_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaevento',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='usuarios.evento'),
        ),
    ]
