# Generated by Django 5.0 on 2023-12-31 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_diaevento_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='horario',
        ),
    ]
