# Generated by Django 5.0 on 2024-01-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_reserva_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='data_hora_fim',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_hora_inicio',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='limite_reservas',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='qtd_max_adultos',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='qtd_max_criancas',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='data_final',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='horario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='dia_evento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Evento'),
        ),
    ]
