# Generated by Django 5.0 on 2024-01-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='title',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='image',
        ),
        migrations.AddField(
            model_name='foto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
